export const ROLE_OPTIONS = [
  'Social Media Manager',
  'Account Manager',
  'Art Director',
  'Brand Designer',
  'Community Manager',
  'Content Creator',
  'Copywriter',
  'Creative Strategist',
  'Graphic Designer',
  'Growth Strategist',
  'Marketing Specialist',
  'Motion Designer',
  'Project Manager',
  'UX/UI Designer',
  'Video Editor',
  'Web Designer',
]

export const EXPERIENCE_LEVEL_OPTIONS = [
  'Creative Director / Lead',
  'Senior',
  'Semi Senior',
  'Mid',
  'Junior',
  'Trainee',
]

export const CURRENT_STATUS_OPTIONS = [
  'Trabajando full-time',
  'Freelanceando activamente',
  'Entre proyectos',
  'Buscando algo nuevo',
  'Estudiando',
  'Tomándome un descanso',
]

export const SKILL_OPTIONS = [
  '3D Modeling',
  'AI Image Generation',
  'Animation',
  'Art Direction',
  'Brand Strategy',
  'Branding',
  'Budget & Timeline Management',
  'Copywriting',
  'Deck Design',
  'Editorial Design',
  'Font Design',
  'Illustration',
  'Logo Design',
  'Mapping',
  'Marketing',
  'Motion Graphics',
  'Paid Media',
  'Photography',
  'Planning',
  'Project Management',
  'SEO',
  'Social Media Strategy',
  'Storytelling',
  'Trend Hunting',
  'UI Design',
  'Video Editing',
  'Web Design',
]

export const TOOL_OPTIONS = [
  'Adobe After Effects',
  'Adobe Illustrator',
  'Adobe InDesign',
  'Adobe Photoshop',
  'Adobe Premiere',
  'Apple Keynote',
  'Blender',
  'Canva',
  'CapCut',
  'Cargo',
  'ChatGPT',
  'Cinema 4D',
  'Claude',
  'DaVinci Resolve',
  'ElevenLabs',
  'Figma',
  'Final Cut Pro',
  'Framer',
  'Google Ads',
  'LinkedIn Campaign Manager',
  'Meta Business Suite',
  'Microsoft PowerPoint',
  'Midjourney',
  'Notion',
  'Runway ML',
  'Slack',
  'Stable Diffusion',
  'TikTok Analytics',
  'Trello',
]

export const WORK_EXPERIENCE_OPTIONS = [
  'Agencia',
  'Productora',
  'Estudio',
  'Freelance',
  'Estudiante',
]

export const FOUND_US_OPTIONS = [
  'Post de Instagram',
  'Historia de Instagram',
  'Threads',
  'LinkedIn',
  'X',
  'A través de un amigo/a',
  'Programa de mano',
  'Vi un post y me dio curiosidad',
  'Desde un anuncio',
  'No estoy seguro/a',
]
